---
- name: Create bucket - {{ entry.name }}
  poc.minio.minio_bucket:
    name: "{{ entry.name }}"
    auth:
      url: "{{ server.url }}"
      access_key: "{{ server.access_key }}"
      secret_key: "{{ server.secret_key }}"
    state: present

- name: Set bucket quota - {{ entry.name }}
  poc.minio.minio_bucket_quota:
    bucket: "{{ entry.name }}"
    size: "{{ entry.size }}"
    auth:
      url: "{{ server.url }}"
      access_key: "{{ server.access_key }}"
      secret_key: "{{ server.secret_key }}"
  when: entry.size is defined
