---
- name: Converge
  hosts: kess
  gather_facts: false
  tasks:
    - name: Audit MinIO
      ansible.builtin.include_role:
        name: poc.minio.minio
      vars:
        role: audit
        lib_arguments:
          server: "{{ minio_server }}"

    - name: Persist audit result
      ansible.builtin.copy:
        content: "{{ minio_audit | to_json }}"
        dest: /tmp/minio_audit.json
        mode: "0644"
