namespace: poc
name: minio
version: 1.0.0
readme: README.md
description: Ansible collection for configuring MinIO
authors:
  - Daniel <phamdaniel64000@gmail.com>
license:
  - MIT
dependencies: {}
build_ignore:
  - .venv
  - "*.tar.gz"
