---
- name: Create user - {{ entry.name }}
  poc.minio.minio_user:
    access_key: "{{ entry.name }}"
    secret_key: "{{ entry.secret_key }}"
    policy: "{{ entry.policy }}"
    auth:
      url: "{{ server.url }}"
      access_key: "{{ server.access_key }}"
      secret_key: "{{ server.secret_key }}"
    state: present
  no_log: true
