---
- name: Verify
  hosts: kess
  gather_facts: false
  tasks:
    - name: Audit MinIO state - present
      ansible.builtin.include_tasks: ../_tasks/audit.yml
      vars:
        minio_expected: present
