---
- name: Prepare kess
  hosts: kess
  gather_facts: false
  tasks:
    - name: Wait for MinIO to be ready
      ansible.builtin.include_tasks: ../_fixtures/wait_for_minio.yml

    - name: Seed MinIO state
      ansible.builtin.include_tasks: ../_fixtures/seed_full_state.yml
