---
- name: Verify
  hosts: kess
  gather_facts: false
  tasks:
    - name: Audit MinIO state - absent
      ansible.builtin.include_tasks: ../tasks/audit.yml
      vars:
        minio_expected: absent
