---
- name: Manage group - {{ entry.name }}
  poc.minio.minio_group:
    name: "{{ entry.name }}"
    members: "{{ entry.members | default([]) }}"
    policy: "{{ entry.policy | default(omit) }}"
    auth:
      url: "{{ lib_arguments.server.url }}"
      access_key: "{{ lib_arguments.server.access_key }}"
      secret_key: "{{ lib_arguments.server.secret_key }}"
    state: "{{ entry.state | default(minio_state | default('present')) }}"
