---
- name: Manage service account
  poc.minio.minio_service_account:
    access_key: "{{ entry.name }}"
    secret_key: "{{ entry.secret_key | default(omit) }}"
    user: "{{ entry.user | default(omit) }}"
    statements: "{{ entry.statements | default(omit) }}"
    auth:
      url: "{{ lib_arguments.server.url }}"
      access_key: "{{ lib_arguments.server.access_key }}"
      secret_key: "{{ lib_arguments.server.secret_key }}"
    state: "{{ entry.state | default(_minio_state) }}"
  no_log: false
  loop: "{{ lib_arguments.entries.service_accounts | default([]) }}"
  loop_control:
    loop_var: entry
    label: "{{ entry.name }}"
