---
- name: Manage user
  poc.minio.minio_user:
    access_key: "{{ entry.name }}"
    secret_key: "{{ entry.secret_key | default(omit) }}"
    policy: "{{ entry.policy | default(omit) }}"
    auth:
      url: "{{ lib_arguments.server.url }}"
      access_key: "{{ lib_arguments.server.access_key }}"
      secret_key: "{{ lib_arguments.server.secret_key }}"
    state: "{{ entry.state | default(_minio_state) }}"
  no_log: false
  loop: "{{ lib_arguments.entries.users | default([]) }}"
  loop_control:
    loop_var: entry
    label: "{{ entry.name }}"
