---
- name: Converge
  hosts: runner
  gather_facts: false
  tasks:
    - name: Configure MinIO
      ansible.builtin.include_role:
        name: configure
      vars:
        server: "{{ minio_server }}"
        entries: "{{ test_minio_entries }}"
