---
- name: Verify
  hosts: runner
  gather_facts: false
  vars:
    _auth:
      url: "{{ minio_server.url }}"
      access_key: "{{ minio_server.access_key }}"
      secret_key: "{{ minio_server.secret_key }}"
  tasks:
    - name: Verify bucket exists - {{ item.name }}
      poc.minio.minio_bucket:
        name: "{{ item.name }}"
        auth: "{{ _auth }}"
        state: present
      loop: "{{ test_minio_entries.buckets }}"
      loop_control:
        label: "{{ item.name }}"
      register: bucket_verify
      changed_when: false

    - name: Assert buckets were not recreated (idempotence)
      ansible.builtin.assert:
        that:
          - not item.changed
        fail_msg: "Le bucket {{ item.item.name }} n'existait pas ou a été recréé"
        success_msg: "Bucket {{ item.item.name }} présent OK"
      loop: "{{ bucket_verify.results }}"
      loop_control:
        label: "{{ item.item.name }}"

    - name: Verify user exists - {{ item.name }}
      poc.minio.minio_user:
        access_key: "{{ item.name }}"
        auth: "{{ _auth }}"
        state: present
      loop: "{{ test_minio_entries.users }}"
      loop_control:
        label: "{{ item.name }}"
      register: user_verify
      changed_when: false
      no_log: true

    - name: Assert users were not recreated (idempotence)
      ansible.builtin.assert:
        that:
          - not item.changed
        fail_msg: "L'utilisateur {{ item.item.name }} n'existait pas ou a été recréé"
        success_msg: "User {{ item.item.name }} présent OK"
      loop: "{{ user_verify.results }}"
      loop_control:
        label: "{{ item.item.name }}"
