---
- name: Manage MinIO resources
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Audit MinIO
      ansible.builtin.include_role:
        name: poc.minio.minio
      vars:
        role: audit
        lib_arguments:
          server: "{{ sys_storage_server }}"
